#Data 601 Project Breast cancer statistics


*   As mentioned in the readme file, we will be working with 2 datasets. One of them will be the 'main' dataset, the other will be reference dataset.
*   The point of the reference dataset is to provide analysis on the guiding question 'breast cancer survivability rate in USA and Canada'

Title of the Project: Breast cancer statistics

Team Name: Team 7

Team members: Lamis Samatar, Romith Bodanda, Gautham Nagaraj

Introduction:

In [ ]:
#import the necessary libraries required for the project
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#Read both of the datasets
seer_data = pd.read_csv('https://raw.githubusercontent.com/Gautham-Nagaraj/Data-601-Project/main/SEER%20Breast%20Cancer%20Dataset%20.csv')
survivability_estimate_canada = pd.read_csv('https://raw.githubusercontent.com/Gautham-Nagaraj/Data-601-Project/main/Survivability%20Estimate%20for%20cancer.csv')

### Now we take a look at what the SEER data looks like, as it is our 'main dataset'.
The survivability estimate data will be examined once the SEER data has been pre-processed.

In [ ]:
seer_data.head()

,Age,Race,Marital Status,Unnamed: 3,T Stage,N Stage,6th Stage,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,43,"Other (American Indian/AK Native, Asian/Pacifi...",Married (including common law),NaN,T2,N3,IIIC,Moderately differentiated; Grade II,Regional,40,Positive,Positive,19,11,1,Alive
1,47,"Other (American Indian/AK Native, Asian/Pacifi...",Married (including common law),NaN,T2,N2,IIIA,Moderately differentiated; Grade II,Regional,45,Positive,Positive,25,9,2,Alive
2,67,White,Married (including common law),NaN,T2,N1,IIB,Poorly differentiated; Grade III,Regional,25,Positive,Positive,4,1,2,Dead
3,46,White,Divorced,NaN,T1,N1,IIA,Moderately differentiated; Grade II,Regional,19,Positive,Positive,26,1,2,Dead
4,63,White,Married (including common law),NaN,T2,N2,IIIA,Moderately differentiated; Grade II,Regional,35,Positive,Positive,21,5,3,Dead

In [ ]:
seer_data.describe()

,Age,Unnamed: 3,Tumor Size,Regional Node Examined,Reginol Node Positive,Survival Months
count,4024.000000,0.0,4024.000000,4024.000000,4024.000000,4024.000000
mean,53.972167,NaN,30.473658,14.357107,4.158052,71.297962
std,8.963134,NaN,21.119696,8.099675,5.109331,22.921430
min,30.000000,NaN,1.000000,1.000000,1.000000,1.000000
25%,47.000000,NaN,16.000000,9.000000,1.000000,56.000000
50%,54.000000,NaN,25.000000,14.000000,2.000000,73.000000
75%,61.000000,NaN,38.000000,19.000000,5.000000,90.000000
max,69.000000,NaN,140.000000,61.000000,46.000000,107.000000

In [ ]:
#Return the number of rows and columns
seer_data.shape

(4024, 16)

In [ ]:
#The following line of code checks for null values and returns a boolean value True or False
#The sum function adds the True values (as 1) and gives us the total missing columns
seer_data.isna().sum()

Age                          0
Race                         0
Marital Status               0
Unnamed: 3                4024
T Stage                      0
N Stage                      0
6th Stage                    0
Grade                        0
A Stage                      0
Tumor Size                   0
Estrogen Status              0
Progesterone Status          0
Regional Node Examined       0
Reginol Node Positive        0
Survival Months              0
Status                       0
dtype: int64

In [ ]:
#The above data clearly indicates that the column 'Unanamed: 3' has no data at all and can be dropped entirely.
seer_data = seer_data.drop('Unnamed: 3', axis=1)
seer_data.isna().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [ ]:
#We can verify that the column has been dropped by checking the shape again.
seer_data.shape

(4024, 15)

In [ ]:
#Get the data type of each column by iterating thorugh each column and using the dtype method
for col in seer_data.columns:
  print("The data type of {}".format(col), "is :{}".format(seer_data[col].dtype))

The data type of Age is :int64
The data type of Race  is :object
The data type of Marital Status is :object
The data type of T Stage  is :object
The data type of N Stage is :object
The data type of 6th Stage is :object
The data type of Grade is :object
The data type of A Stage is :object
The data type of Tumor Size is :int64
The data type of Estrogen Status is :object
The data type of Progesterone Status is :object
The data type of Regional Node Examined is :int64
The data type of Reginol Node Positive is :int64
The data type of Survival Months is :int64
The data type of Status is :object

It is important to keep in mind what the data type of each column is, as some columns which appear numerical actually have catergorical values.
Based on the guiding question we need to calculate the survavability rate, thus we need to modify the 'Status' column to numerical or boolean values so that we can sum them and get the survivability rate.

In [ ]:
#Using the replace method to convert the categorical values to numerical values.
#Now we can sum the column 'Status' and divide it by the total entries to get the survivability rate.
#https://www.geeksforgeeks.org/convert-a-dataframe-column-to-integer-in-pandas/
seer_data['Status'] = seer_data['Status'] .replace({'Alive': 1,'Dead':0}, regex=True).astype(int)
seer_data.head()

<ipython-input-10-d72631ff544a>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  seer_data['Status'] = seer_data['Status'] .replace({'Alive': 1,'Dead':0}, regex=True).astype(int)

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,43,"Other (American Indian/AK Native, Asian/Pacifi...",Married (including common law),T2,N3,IIIC,Moderately differentiated; Grade II,Regional,40,Positive,Positive,19,11,1,1
1,47,"Other (American Indian/AK Native, Asian/Pacifi...",Married (including common law),T2,N2,IIIA,Moderately differentiated; Grade II,Regional,45,Positive,Positive,25,9,2,1
2,67,White,Married (including common law),T2,N1,IIB,Poorly differentiated; Grade III,Regional,25,Positive,Positive,4,1,2,0
3,46,White,Divorced,T1,N1,IIA,Moderately differentiated; Grade II,Regional,19,Positive,Positive,26,1,2,0
4,63,White,Married (including common law),T2,N2,IIIA,Moderately differentiated; Grade II,Regional,35,Positive,Positive,21,5,3,0

In [ ]:
#Verifying that there are no null values, which may have been populated by the replace method.
seer_data['Status'].isna().sum()

0

Our other guiding question is to understand what the survivability rate of a patient is based on thier race.
We can group the data by the race and survivability rate to help answer this question.

In [ ]:
stats_race = pd.pivot_table(seer_data, index='Race ', values='Status', aggfunc='mean')
print(stats_race)

                                                      Status
Race
Black                                               0.749141
Other (American Indian/AK Native, Asian/Pacific...  0.896875
White                                               0.850571

The above table gives us the survivability of each race mentioned in the data set.
Note that these race groups have been grouped in one category 'Other' - American Indian, AK Native, Asian, Pacific Islander.
From the pivot table it is clear that the black demographic has the lowest survivability compared to other races.
This could be due to the patients age being too high or the number of patients.
Let us examine these further in the following code blocks.

In [ ]:
print("Number of 'other' race patients in the group: ",seer_data.loc[seer_data['Race ']== 'Other (American Indian/AK Native, Asian/Pacific Islander)'].agg('count').iloc[0])
print("Number of white race patients in the group: ",seer_data.loc[seer_data['Race ']== 'White'].agg('count').iloc[0])
print("Number of black race patients in the group: ",seer_data.loc[seer_data['Race ']== 'Black'].agg('count').iloc[0])

Number of 'other' race patients in the group:  320
Number of white race patients in the group:  3413
Number of black race patients in the group:  291

In [ ]:
#The above code was performed using the boolean indexing, deriving the count from the individual column based on a condition.
#https://stackoverflow.com/questions/45759966/counting-unique-values-in-a-column-in-pandas-dataframe-like-in-qlik
#It is clear that the number of black patients overall are less compared to other race groups, which could affect the survivability rate.

In [ ]:
#let us observe the average age of the patients by race
#We need to create  a new pivot table to include values by 'age'
stats_race_age = pd.pivot_table(seer_data, index='Race ', values='Age', aggfunc='mean')
print(stats_race_age)

                                                          Age
Race
Black                                               52.580756
Other (American Indian/AK Native, Asian/Pacific...  51.431250
White                                               54.329036

In [ ]:
#So we can eliminate age as a bias, since the average age of all the demographics are close, aprroximately 52

Moving on to the next guiding question: 'Survivability based on Marital Status'

In [ ]:
#Let us a create a pivot table as done previously
stats_marital_status = pd.pivot_table(seer_data, index='Marital Status', values='Status', aggfunc='mean')
print(stats_marital_status.sort_values(by = 'Status'))

                                  Status
Marital Status
Separated                       0.666667
Widowed                         0.791489
Divorced                        0.814815
Single (never married)          0.830894
Married (including common law)  0.864548

In [ ]:
#This table gives us some interseting stats based on a patient's martial status
for cols in seer_data['Marital Status'].unique():
  print("Number of {} ".format(cols), "patients in the dataset: ",seer_data.loc[seer_data['Marital Status']== cols].agg('count').iloc[0])

#Instead of maunally typing print statements we can use a for loop and iterate through the 'unique' data in Marital status and get the total count.
#https://www.geeksforgeeks.org/how-to-count-distinct-values-of-a-pandas-dataframe-column/

Number of Married (including common law)  patients in the dataset:  2643
Number of Divorced  patients in the dataset:  486
Number of Single (never married)  patients in the dataset:  615
Number of Widowed  patients in the dataset:  235
Number of Separated  patients in the dataset:  45

In [ ]:
#The distribution of pateients across the martital status can have a little bias.
#It is better to visualize the data rather than print them out in this fashion.

Moving on to our next guiding question:
What is the survivability rate of a patient living in Canada vs the USA

It has been stated that the USA is leading in cancer treatment by multiple sources:

https://www.insidermonkey.com/blog/5-best-countries-for-cancer-treatment-1140271/5/

https://finance.yahoo.com/news/15-best-countries-cancer-treatment-113926880.html

Where Canada ranks 7 on the list.
We will, through the datasets we have, study whether this is true or not by measuring the survivability rate for each country.

In [ ]:
#The SEER dataset, or the 'main' dataset is from the USA.
#The second dataset we are using is from Canada obtained from statCan.
#We will be comparing these two datasets for survivability rate and make a prediction.

In [ ]:
survivability_estimate_canada.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Primary types of cancer (ICD-O-3),Characteristics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1992/1994,Canada,2016A000011124,"Total, 15 to 99 years",Both sexes,Lip [C00.0-C00.9],Number of eligible cases,Number,223,units,0,v1001639634,1.1.1.1.1,1793.0,NaN,NaN,NaN,0
1,1992/1994,Canada,2016A000011124,"Total, 15 to 99 years",Both sexes,Lip [C00.0-C00.9],5-year net survival,Percentage,242,units,0,v1001639635,1.1.1.1.2,92.0,NaN,NaN,NaN,0
2,1992/1994,Canada,2016A000011124,"Total, 15 to 99 years",Both sexes,Lip [C00.0-C00.9],"Low 95% confidence interval, 5-year net survival",Percentage,242,units,0,v1001639636,1.1.1.1.3,88.0,NaN,NaN,NaN,0
3,1992/1994,Canada,2016A000011124,"Total, 15 to 99 years",Both sexes,Lip [C00.0-C00.9],"High 95% confidence interval, 5-year net survival",Percentage,242,units,0,v1001639637,1.1.1.1.4,95.0,NaN,NaN,NaN,0
4,1992/1994,Canada,2016A000011124,"Total, 15 to 99 years",Both sexes,Tongue [C01.9-C02.9],Number of eligible cases,Number,223,units,0,v1001639638,1.1.1.2.1,1657.0,NaN,NaN,NaN,0